package constants

const val EMPTY_STRING = ""
const val SPACE_STRING = " "

const val COLOR_WHITE = "#ffffff"
const val COLOR_PROPERTY = "color"

const val PLACEHOLDER = "placeholder"
const val FORM_CONTROL_NAME = "formControlName"
const val FOR_ATTRIBUTE ="for"
const val PHONE = "phone"
const val FIRST_NAME = "firstName"
const val LAST_NAME = "lastName"
const val EMAIL = "email"
const val NAME = "name"
const val AGREE_AMS_ID = "agreeAms"
const val LABEL = "label"
const val INPUT = "input"
const val DIV = "div"

const val LOGIN = "login"

const val FORM_CONTROL_NAME_ALL_LOW = "formcontrolname"
const val MESSAGE = "message"
const val DAY = "day"
const val MONTH = "month"
const val YEAR = "year"
const val ADDRESS_ONE = "address1"
const val ADDRESS_TWO = "address2"
const val ZIP = "zip"
const val CITY = "city"
const val RECEIVER_NAME = "receiverName"
const val BANK_NAME = "bankName"
const val BANK_BRANCH_CITY = "bankBranchCity"
const val IBAN = "iban"
const val VAT_NUMBER = "vatRegistrationNumber"

const val ARIA_LABELLEDBY = "aria-labelledby"
const val REMINDER_SWITCHER = "reminderSwitcher"

const val FOLLOWING_SIBLING_DIV = "/following-sibling::div"
const val FOLLOWING_SIBLING_BUTTON = "/following-sibling::button"
const val FOLLOWING_SIBLING_SELECT_CONTROL = "/following-sibling::select-control"
const val PRECEDING_SIBLING_INPUT = "/preceding-sibling::input"

const val DROPDOWN_MENU_CLASS = "dropdown-menu"
const val DROPDOWN_ITEM_CLASS = "dropdown-item"
const val ACTIVE_SIDEBAR_TAB_CLASS = "v-sidebar_item v-sidebar_item--active"
const val LANDING_CLASS = "v-landing"
const val LANDING_SIGN_CLASS = "${LANDING_CLASS}_sign"

//Header Block
const val ID_NAV = "nav"
const val HEADER_SUPPORT_LINK_PATH = "/a[1]"
const val LOGIN_LINK_PATH = "/a[2]"
const val LANGUAGE_LINK_PATH = "/a[3]"

//Main page
const val APPLY_NOW_BUTTON_PATH = "/button"
const val FIXED_HEADER_CLASS = "${LANDING_CLASS}_header_line clearfix ${LANDING_CLASS}_header_line--fixed"
const val JOIN_ME_BUTTON_PATH = "/div[2]/swiper/div/div[1]/div[1]/button"
const val JOIN_TEAM_VIAVAN_LINK = "/html/body/via-app/div/proxy-home/div/div[1]/div[2]/span"
const val WE_ARE_COMING_LINK = "/html/body/via-app/div/proxy-home/div/div[1]/div[2]/div/div/div"
const val ADVANTAGES_TITLE_LINK_PATH = "/div[1]/div[1]"
const val LOWEST_SERVICE_TITLE_PATH = "/div[1]/div[2]/div[1]/div[2]"
const val EARN_MORE_TEXT_PATH = "/div[1]/div[2]/div[1]/div[3]"
const val THE_EARNINGS_TITLE_PATH = "/div[1]/div[2]/div[2]/div[2]"
const val START_EARNING_TEXT_PATH = "/div[1]/div[2]/div[2]/div[3]"
const val LIVE_SUPPORT_TITLE_PATH = "/div[1]/div[3]/div[1]/div[2]"
const val TEXT_WITH_A_PERSON_TEXT_PATH = "/div[1]/div[3]/div[1]/div[3]"
const val INDUSTRY_LEADING_TITLE_PATH = "/div[1]/div[3]/div[2]/div[2]"
const val WE_MAKE_YOUR_LIFE_TEXT_PATH = "/div[1]/div[3]/div[2]/div[3]"
const val EN_LINK_NL_TEXT = "Engels"

//Footer Block
const val ID_PAGE_CONTENT = "pageContent"
const val VIA_VAN_LINK_PATH = "/div[3]/div[1]/a[1]"
const val FOOTER_SUPPORT_LINK_PATH = "/div[3]/div[1]/a[2]"
const val PRIVACY_POLICY_LINK_PATH = "/div[3]/div[1]/a[3]"
const val TERMS_LINK_PATH = "/div[3]/div[1]/a[4]"
const val SUPPORT_POP_UP_XPATH = "/html/body/modal-overlay/bs-modal-container/div/div/contact_us/form"
const val SUPPORT_POP_UP_CLOSE_XPATH = "/html/body/modal-overlay/bs-modal-container/div/div/contact_us/form/div/div[1]/div/button"

//Login Block
const val LOGIN_ICON_CLASS = "posa"
const val LOGIN_CODE_TAG = "phone-code-select"
const val SIGNUP_LINK_CLASS = "${LANDING_SIGN_CLASS}_subtext--blue ml2"
const val LOGIN_BUTTON_CLASS = "${LANDING_SIGN_CLASS}_row phone-code"
const val VERIF_TOKEN_NAME = "verificationToken"
const val LOGIN_TITLE_ID1 = "loginTitle1"
const val LOGIN_MESSAGE_XPATH = "//*[@id=\"login\"]/form[1]/div[2]"
const val LOGIN_PHONE_LABEL_XPATH = "//*[@id=\"login\"]/form[1]/div[3]/div/label"
const val LOGIN_BUTTON_XPATH = "//*[@id=\"login\"]/form[1]/button"
const val LOGIN_TO_SIGN_UP_LINK_XPATH = "//*[@id=\"login\"]/form[1]/div[4]/span"
const val LOGIN_PHONE_ERROR_TOOLTIP = "//*[@id=\"login\"]/form[1]/div[3]/div/div"
const val PENDING_TITLE_CLASS = "${LANDING_SIGN_CLASS}__title--centered mt155 mb15"
const val PENDING_TEXT_CLASS = "${LANDING_SIGN_CLASS}__text--centered"
const val LOGIN_TITLE_CLASS = "${LANDING_SIGN_CLASS}__title"

const val VERIF_CODE_SENT_TEXT_XPATH = "form/div[2]"
const val WRONG_PHONE_NUM_LINK_XPATH = "form/a"
const val VERIF_CODE_LABEL_XPATH = "form/div[3]/div/label"
const val VERIF_CODE_CONTINUE_XPATH = "form/button"
const val RESENDING_CODE_LINK_XPATH = "form/a[2]"
const val RESENDING_CODE_TEXT_XPATH = "form/span"
const val SIGNUP_HERE_TEXT_CLASS = "tac"

//CarouselBlock
const val CAROUSEL_PREVIOUS_BUTTON_PATH = "/div[2]/swiper/div/div[4]"
const val CAROUSEL_NEXT_BUTTON_PATH = "/div[2]/swiper/div/div[3]"
const val CAROUSEL_FIRST_ELEMENT_PATH = "/div[2]/swiper/div/div[1]/div[1]"
const val CAROUSEL_SECOND_ELEMENT_PATH = "/div[2]/swiper/div/div[1]/div[2]"
const val CAROUSEL_THIRD_ELEMENT_PATH = "/div[2]/swiper/div/div[1]/div[3]"
const val CAROUSEL_FOURTH_ELEMENT_PATH = "/div[2]/swiper/div/div[1]/div[4]"
const val CAROUSEL_FIRST_ELEMENT_TEXT_PATH = "/div[2]/swiper/div/div[1]/div[1]/p"
const val CAROUSEL_SECOND_ELEMENT_TEXT_PATH = "/div[2]/swiper/div/div[1]/div[2]/p"
const val CAROUSEL_THIRD_ELEMENT_TEXT_PATH = "/div[2]/swiper/div/div[1]/div[3]/p"
const val CAROUSEL_FOURTH_ELEMENT_TEXT_PATH = "/div[2]/swiper/div/div[1]/div[4]/p"
const val CAROUSEL_FIRST_ELEMENT_DRIVER_PARTNER_PATH = "/div[2]/swiper/div/div[1]/div[1]/div/ul/li[2]"
const val CAROUSEL_SECOND_ELEMENT_DRIVER_PARTNER_PATH = "/div[2]/swiper/div/div[1]/div[2]/div/ul/li[2]"
const val CAROUSEL_THIRD_ELEMENT_DRIVER_PARTNER_PATH = "/div[2]/swiper/div/div[1]/div[3]/div/ul/li[2]"
const val CAROUSEL_FOURTH_ELEMENT_DRIVER_PARTNER_PATH = "/div[2]/swiper/div/div[1]/div[4]/div/ul/li[2]"
const val CAROUSEL_FIRST_ELEMENT_BUTTON_PATH = "/div[2]/swiper/div/div[1]/div[1]/button"
const val CAROUSEL_SECOND_ELEMENT_BUTTON_PATH = "/div[2]/swiper/div/div[1]/div[2]/button"
const val CAROUSEL_THIRD_ELEMENT_BUTTON_PATH = "/div[2]/swiper/div/div[1]/div[3]/button"
const val CAROUSEL_FOURTH_ELEMENT_BUTTON_PATH = "/div[2]/swiper/div/div[1]/div[4]/button"

//test data
const val LOGIN_PHONE_NUM_AMS = "787656634"
const val AMS_PHONE_CODE = "+31"

//Sign Up Block
const val LINK_TO_LOGIN_CLASS = "${LANDING_SIGN_CLASS}__link"
const val SIGNUP_NEXT_BUTTON_CLASS = "${LANDING_SIGN_CLASS}__button"
const val VIAVAN_TERMS_OF_USE_LINK_TEXT = "ViaVan’s Terms of Use"
const val VIAVAN_PRIVACY_POLICY_LINK_TEXT = "ViaVan’s Privacy Policy."
const val SIGNUP_ID = "signUp"
const val SIGNUP_AGREE_CLASS = "signup__text-agree"

//Questionnaire Block
const val QUESTIONNAIRE_BLOCK_XPATH = "//div[contains(@class, 'question')]"
const val QUESTIONNAIRE_NEXT_BUTTON_ID = "questionnaireNext"
const val ISSUE_COLLECTION = ".signup__issues_item"
const val QUESTIONNAIRE_BLOCK_SELECT_ITEM_XPATH = "//*[contains(@class, 'signup__quest')]/input"
const val QUESTIONNAIRE_ISSUE_MESSAGE_CLASS = "signup__issues_item"
const val SIGN_FORM_CLASS = "v-landing_header_sign"
const val SPINNER_CLASS = "v-landing_sign__loader"
const val QUEST_YES_TEXT = "Yes"
const val QUEST_REF_DRIVER = "Referred by ViaVan Driver Partner"
const val QUEST_FACEBOOK = "Facebook"

//Profile Info Block
const val PERCENT_TEXT_CSS_SELECTOR = ".v-sidebar_item"
const val SAVE_AND_NEXT_BUTTON_CLASS = "v-header_button"
const val POPUP_CLASS = "popup-title"
const val CLOSE_BUTTON_CLASS = "close"
const val POPUP_SEND_BUTTON_CLASS = "btn btn-success btn-md"
const val DOB_EMPTY_ERROR_TOOLTIP_XPATH = "/html/body/via-app/div/layout/div/driver-info/form/div/div[5]/div[5]/div/div[3]"
const val DOB_PART_ERROR_TOOLTIP_XPATH = "/html/body/via-app/div/layout/div/driver-info/form/div/div[6]/div[5]/div/div[3]"
const val DOB_DAY_LIST_XPATH = "/html/body/via-app/div/layout/div/driver-info/form/div/div[4]/div[5]/div/div[2]/date-picker/" +
        "form/select-control[1]/a/div/a[@class=\"dropdown-item ${LANDING_CLASS}_dropdown_menu__item\"]"
const val DOB_MONTH_LIST_XPATH = "/html/body/via-app/div/layout/div/driver-info/form/div/div[4]/div[5]/div/div[2]/date-picker/" +
        "form/select-control[2]/a/div/a[@class=\"dropdown-item ${LANDING_CLASS}_dropdown_menu__item\"]"
const val DOB_YEAR_LIST_XPATH = "/html/body/via-app/div/layout/div/driver-info/form/div/div[4]/div[5]/div/div[2]/date-picker/" +
        "form/select-control[3]/a/div/a[@class=\"dropdown-item ${LANDING_CLASS}_dropdown_menu__item\"]"
const val ZIP_ERROR_TOOLTIP_XPATH = "/html/body/via-app/div/layout/div/driver-info/form/div/div[6]/div/div[1]/div[3]"
const val ERROR_ON_TOP_CLASS = "red-error"
const val PROFILE_UPLOAD_INPUT_ID = "0"
const val PROFILE_IMAGE_UPDATE_XPATH = "/html/body/via-app/div/layout/div/driver-info/form/div/div[3]/upload/div/div[2]/div[2]/label"
const val PROFILE_IMAGE_XPATH = "/html/body/via-app/div/layout/div/driver-info/form/div/div[3]/upload/div/div[2]/img"
const val TAXI_UPLOAD_INPUT_ID = "1"
const val TAXI_IMAGE_UPDATE_XPATH = "/html/body/via-app/div/layout/div/driver-info/form/div/div[7]/upload/div/div[2]/div[2]/label"
const val TAXI_IMAGE_XPATH = "/html/body/via-app/div/layout/div/driver-info/form/div/div[7]/upload/div/div[2]/img"
const val PRO_DRIVER_LICENSE_UPLOAD_INPUT_ID = "2"
const val PROD_DRIVER_LICENSE_IMAGE_UPDATE_XPATH = "/html/body/via-app/div/layout/div/driver-info/form/div/div[8]/upload/div/div[2]/div[2]/label"
const val PRO_DRIVER_LICENSE_IMAGE = "/html/body/via-app/div/layout/div/driver-info/form/div/div[8]/upload/div/div[2]/img"
const val BACK_DRIVER_LICENSE_UPLOAD_INPUT_ID = "3"
const val BACK_DRIVER_LICENSE_IMAGE_UPDATE_XPATH = "/html/body/via-app/div/layout/div/driver-info/form/div/div[9]/upload/div/div[2]/div[2]/label"
const val BACK_DRIVER_LICENSE_IMAGE = "/html/body/via-app/div/layout/div/driver-info/form/div/div[9]/upload/div/div[2]/img"
const val FRONT_DRIVER_LICENSE_UPLOAD_INPUT_ID = "4"
const val FRONT_DRIVER_LICENSE_IMAGE_UPDATE_XPATH = "/html/body/via-app/div/layout/div/driver-info/form/div/div[10]/upload/div/div[2]/div[2]/label"
const val FRONT_DRIVER_LICENSE_IMAGE = "/html/body/via-app/div/layout/div/driver-info/form/div/div[10]/upload/div/div[2]/img"
const val TRAMWAY_UPLOAD_INPUT_ID = "5"
const val TRAMWAY_IMAGE_UPDATE_XPATH = "/html/body/via-app/div/layout/div/driver-info/form/div/div[11]/upload/div/div[2]/div[2]/label"
const val TRAMWAY_IMAGE_XPATH = "/html/body/via-app/div/layout/div/driver-info/form/div/div[11]/upload/div/div[2]/img"
const val PERCENTS_FULL_XPATH = "/html/body/via-app/div/layout/div/sidebar-ams/div/div[1]/div[1]"
const val ERROR_TOOLTIP_CLASS = "${LANDING_CLASS}_info-tooltip"
const val IMAGE_UPLOAD_BAR_CLASS = "v-upload_uploading"

//Vehicle Info Block
const val VEH_TABLE_XPATH = "/html/body/via-app/div/layout/div/driver-vehicle/form/div/div[2]/div"
const val VEH_MAKE_XPATH = "$VEH_TABLE_XPATH/div[1]/div[1]/div[2]/select-control/a/a"
const val VEH_MODEL_XPATH = "$VEH_TABLE_XPATH/div[1]/div[2]/div[2]/select-control/a/a"
const val VEH_COLOR_XPATH = "$VEH_TABLE_XPATH/div[1]/div[3]/div[2]/select-control/a/a"
const val VEH_INTERIOR_XPATH = "$VEH_TABLE_XPATH/div[2]/div[1]/div[2]/select-control/a/a"
const val VEH_YEAR_XPATH = "$VEH_TABLE_XPATH/div[2]/div[2]/div[2]/select-control/a/a"
const val VEH_PLATE_XPATH = "$VEH_TABLE_XPATH/div[2]/div[3]/div[2]/input"
const val VEH_REG_BACK_UPLOAD_INPUT_XPATH = "//div[@class='v-upload_image-place']/input[@id='6']"
const val VEH_REG_BACK_UPDATE_BTN_XPATH = "//*[@id=\"6\"]/parent::div/div[@class='v-upload_update']/label"
const val VEH_REG_BACK_UPLOAD_BAR_XPATH = "//upload[1]//div[@class='v-upload_uploading']"

const val VEH_REG_FRONT_UPLOAD_INPUT_XPATH = "//div[@class='v-upload_image-place']/input[@id='7']"
const val VEH_REG_FRONT_UPDATE_BTN_XPATH = "//*[@id=\"7\"]/parent::div/div[@class='v-upload_update']/label"

const val VEH_INSUR_UPLOAD_INPUT_XPATH = "//div[@class='v-upload_image-place']/input[@id='8']"
const val VEH_INSUR_UPDATE_BTN_XPATH = "//*[@id=\"8\"]/parent::div/div[@class='v-upload_update']/label"

const val VEH_INSPECT_UPLOAD_INPUT_XPATH = "//div[@class='v-upload_image-place']/input[@id='9']"
const val VEH_INSPECT_UPDATE_BTN_XPATH = "//*[@id=\"9\"]/parent::div/div[@class='v-upload_update']/label"

const val VEH_EXTER_UPLOAD_INPUT_XPATH = "//div[@class='v-upload_image-place']/input[@id='10']"
const val VEH_EXTER_UPDATE_BTN_XPATH = "//*[@id=\"10\"]/parent::div/div[@class='v-upload_update']/label"

//Agreements Block
const val AGREEMENTS_HEADER_BLOCK_CLASS = "agreements__header_title"
const val AGREEMENTS_SAVE_AND_NEXT_CLASS = "v-content_button--special"

//Payment Info Block
const val YOU_RADIO_BUTTON_ID = "option3"
const val YOU_RADIO_BUTTON_CONTAINER_XPATH = "//*[@for=\"option4\"]"
const val OTHER_RADIO_BUTTON_XPATH = "//*[@for=\"option4\"]"
const val BANK_NAME_ERROR_TOOLTIP_XPATH = "/html/body/via-app/div/layout/div/deposit-info/form/div/div[6]/div/div[1]/div[3]"
const val BANK_BRANCH_CITY_ERROR_TOOLTIP_XPATH = "/html/body/via-app/div/layout/div/deposit-info/form/div/div[6]/div/div[2]/div[3]"
const val PAYABLE_NAME_ERROR_TOOLTIP_XPATH = "/html/body/via-app/div/layout/div/deposit-info/form/div/div[5]/div/div/div[3]"
const val INCOMPLETE_POPUP_CLASS = "v-content_dialog"
const val ERROR_CLOSE_BUTTON_CLASS = "red-error_close"
const val PAYMENT_INFO_PERCENTAGES_FULL_XPATH = "/html/body/via-app/div/layout/div/sidebar-ams/div/div[4]/div[1]"

//Almost Done Block
const val GOOGLE_PLAY_BUTTON_CLASS = "v-this_body_google mr20 mr10-xs"
const val APP_STORE_BUTTON_CLASS = "v-this_body_apple"
const val FACEBOOK_BUTTON_CLASS = "v-this_social__item v-this_social__item--f"
const val TWITTER_BUTTON_CLASS = "v-this_social__item v-this_social__item--t"
const val LINKEDIN_BUTTON_CLASS = "v-this_social__item v-this_social__item--l"
const val PROFILE_IMAGE_CLASS = "v-this_header__no-image"